name: smoke-tests
run-name: Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'

# Limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  smoke-tests-ess:
    name: Run smoke tests ESS
    uses: ./.github/workflows/smoke-tests-ess.yml
    with:
      branch: 'feature/github-actions-ess'
      # branch: 'main'

  smoke-tests-os:
    name: Run smoke tests OS
    strategy:
      matrix:
        branch:
          - 'feature/github-actions-ess'
        #   - main
        #   - 8.7
    uses: ./.github/workflows/smoke-tests-os.yml
    with:
      branch: ${{ matrix.branch }}
