name: smoke-tests
run-name: Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'

# Limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  prepare-smoke-tests-os:
    name: Generate smoke tests list
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      branches: ${{ steps.generate.outputs.branches }}
    steps:
      - uses: actions/checkout@v3
      - id: generate
        name: Generate matrix
        run: |
          echo "branches=$(./.ci/scripts/smoke-tests-matrix.sh)" >> "${GITHUB_OUTPUT}"

  smoke-tests-os:
    name: Run smoke tests OS
    needs: prepare-smoke-tests-os
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.prepare-smoke-tests-os.outputs.branches) }}
    uses: ./.github/workflows/smoke-tests-os.yml
    with:
      # branch: ${{ matrix.branch }}
      branch: ['feature/github-actions-ess']
    secrets: inherit

  smoke-tests-ess:
    name: Run smoke tests ESS
    uses: ./.github/workflows/smoke-tests-ess.yml
    with:
      # branch: 'main'
      branch: 'feature/github-actions-ess'
    secrets: inherit
